apiVersion: apps/v1
kind: Deployment
metadata:
  name: physicalc-backend
  labels:
    app: physicalc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: physicalc-backend
  template:
    metadata:
      labels:
        app: physicalc-backend
    spec:
      containers:
        - name: backend
          image: asia-south1-docker.pkg.dev/adroit-resolver-414008/physicalc-repo/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Mongo URI from secret
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-physicalc-conn
                  key: mongo_uri

            # Postgres connection (can also be moved to a secret later)
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-physicalc-conn
                  key: database_url

            - name: PORT
              value: "8000"